# Config file for automatic testing at travis-ci.com

language: python
python:
  - 3.8
  - 3.7
  # - 3.6
# Command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: pip install -U tox-travis

# Command to run tests, e.g. python setup.py test
script: tox
deploy:
  provider: pypi
  user: manujosephv
  password:
    secure: "TlGnHrmenRnDLEcoEMwkcojidlEzQ37ZdzVmjRIuJ4vo5pMnpqMi4JKIu1yiaMXQTHryLXnquZXn4Z0lgsln85iniRyvEJGfqkjZqzt+q//hroirp5iD3htrhBBJiwHFhdLefHgXHtKVq/GrMDkgWDBC7MYVTNk3IBQy1wqn3sAqJPLxWgqu30LsgiyvPudmcLF9svcWTpRp/BcQQwjoLQs3IhXA/msg5b8sEUp4yH2sSQiT+ltUzLpy3LQcBp7Pi4Ktaq7VDm+8FgfUla8FC0je2Ho/t98bTrN4PZVrM6FHv2/o9XBzy4J8ON+cEjKnimNYk6/Hv1ul+S5B4VE8duEiruYioWbvSz1oNwZi0ecewh7k9WqWQiLPo3KH7jlEEuZmMZrJAl0vHpK/jAxV2MptXp8xF1EWH+GZYWmR9NBOZE0Hov5+v/U+PtT2fhEutuUXzTEPGXUI7tp+ZC1ICZ0iSFRq2MhYK58S+IxB1pBbnhBvFOadnDRdnStLWBTh1xkGmtOjveNpPGdSJGOyTUZXqXgMGkF+Md4HT1KEzdywpkQcGVFmNu+C9d2BUqPUOvDzUpXDtU0646oeeMuP6MNWzztEs+x/p4sdm1CkuL05R+l2zgki0cbxRz1VE43BUywOP/Qk22Vf0fzUhjffd9QbDtQx+EtkHge7Zn2QYBM="
  on:
    tags: true
  skip_existing: true


